# Generated by Django 5.1.10 on 2025-09-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="employees_count",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="UserOrganization",
        ),
    ]
