# Generated by Django 5.1.10 on 2025-09-17 17:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "organizations",
            "0004_alter_organization_options_remove_organization_owner_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="is_org_admin",
        ),
    ]
