# Generated by Django 5.1.10 on 2025-09-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0093_alter_asset_parent_assets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="parent_assets",
            field=models.ManyToManyField(
                blank=True, to="core.asset", verbose_name="parent assets"
            ),
        ),
    ]
